

DROP TABLE IF EXISTS COMMENTAIRE;
DROP TABLE IF EXISTS TACHE;
DROP TABLE IF EXISTS PROJET_MEMBRE;
DROP TABLE IF EXISTS PROJET;
DROP TABLE IF EXISTS UTILISATEUR;

-- CREATION DES TABLES

-- Utilisateurs
CREATE TABLE UTILISATEUR (
UTI_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UTI_NOMUTILISATEUR VARCHAR(50) NOT NULL UNIQUE,
UTI_EMAIL VARCHAR(100) NOT NULL UNIQUE,
UTI_MOTDEPASSE VARCHAR(255) NOT NULL,
UTI_DATECREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Projets
CREATE TABLE PROJET (
PRO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PRO_NOM VARCHAR(100) NOT NULL,
PRO_DESCRIPTION TEXT DEFAULT NULL,
PRO_PROPRIETAIRE_ID INT UNSIGNED NOT NULL,
PRO_DATECREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,


CONSTRAINT FK_PRO_PROPRIETAIRE
    FOREIGN KEY (PRO_PROPRIETAIRE_ID)
    REFERENCES UTILISATEUR (UTI_ID)


);

-- Classe d'association : UTILISATEUR <-> PROJET
CREATE TABLE PROJET_MEMBRE (
PRM_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PRM_PRO_ID INT UNSIGNED NOT NULL,
PRM_UTI_ID INT UNSIGNED NOT NULL,
PRM_ROLE ENUM('proprietaire', 'membre') NOT NULL DEFAULT 'membre',
PRM_DATEADHESION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_PRM_PROJET
    FOREIGN KEY (PRM_PRO_ID)
    REFERENCES PROJET (PRO_ID)
    ON DELETE CASCADE,

CONSTRAINT FK_PRM_UTILISATEUR
    FOREIGN KEY (PRM_UTI_ID)
    REFERENCES UTILISATEUR (UTI_ID)
    ON DELETE CASCADE,

UNIQUE KEY UNIQUE_MEMBRE (PRM_PRO_ID, PRM_UTI_ID)


);

-- Tâches
CREATE TABLE TACHE (
TAC_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TAC_PRO_ID INT UNSIGNED NOT NULL,
TAC_UTI_ID INT UNSIGNED DEFAULT NULL,
TAC_TITRE VARCHAR(150) NOT NULL,
TAC_DESCRIPTION TEXT DEFAULT NULL,
TAC_PRIORITE ENUM('faible', 'moyenne', 'haute') NOT NULL DEFAULT 'moyenne',
TAC_STATUT ENUM('a_faire', 'en_cours', 'terminee') NOT NULL DEFAULT 'a_faire',
TAC_DATEECHEANCE DATE DEFAULT NULL,
TAC_ESTACTIVE TINYINT(1) NOT NULL DEFAULT 1,
TAC_DATECREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_TAC_PROJET
    FOREIGN KEY (TAC_PRO_ID)
    REFERENCES PROJET (PRO_ID)
    ON DELETE CASCADE,

CONSTRAINT FK_TAC_UTILISATEUR
    FOREIGN KEY (TAC_UTI_ID)
    REFERENCES UTILISATEUR (UTI_ID)
    ON DELETE SET NULL


);

-- Commentaires sur les tâches
CREATE TABLE COMMENTAIRE (
COM_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
COM_TAC_ID INT UNSIGNED NOT NULL,
COM_UTI_ID INT UNSIGNED NOT NULL,
COM_CONTENU TEXT NOT NULL,
COM_DATECREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_COM_TACHE
    FOREIGN KEY (COM_TAC_ID)
    REFERENCES TACHE (TAC_ID)
    ON DELETE CASCADE,

CONSTRAINT FK_COM_UTILISATEUR
    FOREIGN KEY (COM_UTI_ID)
    REFERENCES UTILISATEUR (UTI_ID)
    ON DELETE CASCADE


);

COMMIT;
